[package]
name = "julia-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sessionless = "0.1.1"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0"
